### PR TITLE
Repair make targets and ssl/ssldecode.c, bump version

### PR DESCRIPTION
**Pull request by qha**

### CODE REVIEW

**Comment by adulau** [comment]
Thanks a lot!

**Comment by qha** [comment]
My pleasure!

Would you consider tagging master with v0.9b3p1 so Github produces an archive?

**Comment by adulau** [comment]
Sure, great idea! For the past years, I was so frustrated that ssldump has a version below 1.0. So I tagged it with v1.0 and made an release.

https://github.com/adulau/ssldump/releases/tag/v1.0

Thanks again.

**Comment by qha** [comment]
Thank you! The release makes my packaging cleaner.

**Pull request merged**
