### PR TITLE
add save decrypted datato pcap. first alpha version

### PR DESCRIPTION
**Pull request by ryabkov**
add -w filename.pcap option. 
with this decrypted data can be store in pcap. main part came from sslsplit project

### CODE REVIEW

**Comment by adulau** [comment]
Oh great. Thanks a lot. This sounds really neat. I'm trying to add some test in ssldump in the GitHub workflow. Would it possible to add some test pcap files?

**Comment by ryabkov** [comment]
ok. how can I add it?

**Comment by adulau** [comment]
Maybe a test directory with the pcap files used as test and the expected outpout? Thanks a lot.

**Comment by ryabkov** [comment]
> Maybe a test directory with the pcap files used as test and the expected outpout? Thanks a lot.

ок. i will try. main problem - i dont know how to verify correctness automatically(because every new output pcap differ in binary form  from prev output)

**Comment by adulau** [comment]
and if we use only a single fixed pcap?

**Comment by wllm-rbnt** [comment]
I reworked this PR in https://github.com/wllm-rbnt/ssldump/tree/save2pcap
It's now using the new build system. It will be ready for pull request after merge of https://github.com/adulau/ssldump/pull/38

**Comment by wllm-rbnt** [comment]
The new PR is open --> https://github.com/adulau/ssldump/pull/39
Ready for testing.
Documentation has yet to be aligned before merge.

**Pull request merged**
